### ISSUE TITLE
how to populate resize directory

### ISSUE THREAD

**Issue by IRSHAD500THUKROO** [CarloP95/Text2VideoGAN#1]
We don't know how to fill and load resize folder/directory
Kindly tell us the flow of execution , because we are suffering lot of issues while trying to run the code in jupyter

**Comment by CarloP95** [comment]
Hi! Thanks for your interest in this project. 

We didn't do clip resize in our project, as you can see here [Data analysis](https://github.com/CarloP95/Text2VideoGAN/blob/master/1.1%20-%20MoCoGAN%20-%20Exploratory%20Data%20Analysis.ipynb). 

Can i suggest you to look to the official MoCoGAN from nvidia? 

Good luck with your work!
